### vedc configuration

# Configuration format version
version: 2.0.0

## COMMANDS
# The commands section configures the CLI commands.
commands:

  # The override flag can be set to override command configs with user-defined
  # settings. If false, user settings will be merged with the default
  # settings defined here, otherwise user settings will override default
  # settings. This flag is set to true by vedc generate_config.
  override: false

  # Configuration for vedc record.
  record:

    # Target folder for the recording. Can be templated using the Python format
    # syntax (curly braces). Available variables are:
    # - today: current datetime as a datetime.datetime.today instance
    # - cwd: current working directory as a pathlib.Path instance
    # - cfgd: directory containing user config file as a pathlib.Path instance
    # - all metadata fields
    # Example: {cwd}/{subject_id} to record to a folder named after the
    #   subject_id metadata field within the current folder.
    folder: ~/recordings/{today:%Y_%m_%d_%H_%M_%S}

    # Folder creation policy. Available options:
    # - here: record directly to the folder specified by the folder key but
    #     raise an error if files would be overwritten
    # - overwrite: record directly to the folder specified by the folder key
    #     and delete all files within than folder
    # - new_folder: record to a numbered sub-folder (000, 001, ...) within the
    #     folder specified by the folder key
    policy: here

    # Duration of the recording in seconds. Set to null/leave empty to record
    # indefinitely.
    duration: null

    # The video section contains one entry for each video stream to record.
    # Each stream must be defined in the streams.video section. Entries can be
    # set to null/left empty or specify arguments passed to the VideoRecorder
    # process.
    video:
      world:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      eye0:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      eye1:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      t265:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast

    # The motion section contains one entry for each video stream to record.
    # Each stream must be defined in the streams.motion section. Entries can be
    # set to null/left empty or specify arguments passed to the MotionRecorder
    # process.
    motion:
      odometry: null
      accel: null
      gyro: null

    # Set to true to show video windows at the start of the recording.
    show_video: false

    # Metadata that is requested from the user at the start of the recording.
    # When provided as a mapping (like here), values can be set to define
    # defaults that are suggested during input (e.g. study_site: UNR). When
    # provided as a list, or when values are null, no defaults are suggested.
    metadata:
      # experimenter
      study_site: null
      experimenter_id: null
      # experiment
      experiment: null
      lighting: null
      scene: null
      instruction: null
      # subject
      subject_id: null
      age: null
      gender: null
      height: null
      ethnicity: null
      IPD: null
      tilt_angle: null

    # Selector to auto-determine a profile at the start of the recording.
    # The selector has to be defined in the metadata and will use the value
    # of the metadata field to look up a profile. Set to null/leave empty to
    # disable automatic selection.
    profile_selector: lighting

    # Intrinsics for streams that are copied to the recording folder. Each list
    # item specifies a stream name whose 'device_uid' is looked up to copy the
    # corresponding intrinsics file from the folder defined in
    # commands.estimate_cam_params.folder to the recording folder and renamed
    # to the stream name.
    # Example: ~/pupil_capture_settings/19208652.intrinsics is copied to
    #  ~/recordings/2021_01_01_00_00_00/world.intrinsics.
    intrinsics:
      - world

    # Extrinsics for streams that are copied to the recording folder. Each list
    # item specifies a stream name whose 'device_uid' is looked up to copy the
    # corresponding extrinsics file(s) from the folder defined in
    # commands.estimate_cam_params.folder to the recording folder and renamed
    # to the stream name.
    # Example: ~/pupil_capture_settings/19208652.extrinsics is copied to
    #  ~/recordings/2021_01_01_00_00_00/world.extrinsics.
    extrinsics:
      - world
      - t265

  # Configuration for vedc calibrate.
  calibrate:

    # Target folder for storing calibration. Can be templated using the Python
    # format syntax (see commands.record.folder for available options).
    folder: ~/pupil_capture_settings

    # Name of the world camera stream. Has to be defined in streams.video.
    world: world

    # Name of the right eye camera stream. Has to be defined in streams.video.
    eye0: eye0

    # Name of the left eye camera stream. Has to be defined in streams.video.
    eye1: eye1

  # Configuration for vedc validate.
  validate:

    # Target folder for storing validation results. Can be templated using the
    # Python format syntax (see commands.record.folder for available options).
    folder: ~/validations/{today:%Y_%m_%d_%H_%M_%S}

    # Folder creation policy (see commands.record.folder for options).
    policy: here

    # Name of the world camera stream. Has to be defined in streams.video.
    world: world

    # Name of the right eye camera stream. Has to be defined in streams.video.
    eye0: eye0

    # Name of the left eye camera stream. Has to be defined in streams.video.
    eye1: eye1

    # Additional settings passed to processes in the pipeline for each stream.
    # Each entry corresponds to a stream defined in the streams.video section.
    settings:
      world:
        circle_detector:
          scale: 0.5
          paused: true
          marker_size:
            - 5
            - 300
          threshold_window_size: 13
          min_area: 200
          max_area: 4000
          circularity: 0.8
          convexity: 0.7
          inertia: 0.4

  # Configuration for vedc estimate_cam_params.
  estimate_cam_params:

    # Target folder for storing camera parameters. Can be templated using the
    # Python format syntax (see commands.record.folder for available options).
    folder: ~/pupil_capture_settings

    # Additional settings passed to processes in the pipeline for each stream.
    # Each entry corresponds to a stream defined in the streams.video section.
    settings:
      t265:
        circle_grid_detector:
          stereo: true
          scale: 0.75
        cam_param_estimator:
          num_patterns: 15
          grid_scale: 0.02
      world:
        circle_grid_detector:
          scale: 0.5
        cam_param_estimator:
          num_patterns: 15
          grid_scale: 0.02

## STREAMS
# The streams section defines all streams that are used by the CLI commands.
streams:

  # The override flag can be set to override stream configs with user-defined
  # settings. If false, user settings will be merged with the default
  # settings defined here, otherwise user settings will override default
  # settings. This flag is set to true by vedc generate_config.
  override: false

  # The video section defines all video streams. Each entry is mapped directly
  # to a VideoStream.Config and the name of the entry corresponds to the stream
  # name.
  video:
    world:
      device_type: flir
      device_uid: null
      resolution: (2048, 1536)
      fps: 30
      color_format: bayer_rggb8
      settings:
        ExposureAuto: Continuous
        GainAuto: Continuous
    eye0:
      device_type: uvc
      device_uid: Pupil Cam2 ID0
      resolution: (400, 400)
      fps: 120
      color_format: gray
      exposure_mode: auto
      controls:
        Backlight Compensation: 1
        Brightness: 10
        Contrast: 65
        Gain: 0
        Hue: 0
        Saturation: 0
        Sharpness: 3
        Gamma: 120
        White Balance temperature: 4600
    eye1:
      device_type: uvc
      device_uid: Pupil Cam2 ID1
      resolution: (400, 400)
      fps: 120
      color_format: gray
      exposure_mode: auto
      controls:
        Backlight Compensation: 1
        Brightness: 10
        Contrast: 65
        Gain: 0
        Hue: 0
        Saturation: 0
        Sharpness: 3
        Gamma: 120
        White Balance temperature: 4600
    t265:
      device_type: t265
      device_uid: null
      resolution: (1696, 800)
      fps: 30
      color_format: gray

  # The motion section defines all motion streams. Each entry is mapped
  # directly to a MotionStream.Config and the name of the entry corresponds to
  # the stream name.
  motion:
    odometry:
      device_type: t265
      device_uid: null
      motion_type: odometry
    accel:
      device_type: t265
      device_uid: null
      motion_type: accel
    gyro:
      device_type: t265
      device_uid: null
      motion_type: gyro

## PROFILES
# The profiles section defines custom stream settings that can be dynamically
# applied, e.g. based on lighting conditions. Profiles are always merged with
# the settings defined in the streams section and are not intended to
# completely override stream settings.
profiles:

  # The override flag can be set to override profile configs with user-defined
  # settings. If false, user settings will be merged with the default
  # settings defined here, otherwise user settings will override default
  # settings. This flag is set to true by vedc generate_config.
  override: false

  # Profile for indoor recordings.
  indoor:
    video:
      eye0:
        controls:
          Backlight Compensation: 1
          Brightness: 0
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 180
          White Balance temperature: 4600
      eye1:
        controls:
          Backlight Compensation: 1
          Brightness: 0
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 180
          White Balance temperature: 4600

  # Profile for outdoor recordings.
  outdoor:
    video:
      eye0:
        controls:
          Backlight Compensation: 1
          Brightness: -60
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 100
          White Balance temperature: 4600
      eye1:
        controls:
          Backlight Compensation: 1
          Brightness: -60
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 100
          White Balance temperature: 4600
