version: 1.0.0

commands:
  record:
    folder: ~/recordings/{today:%Y_%m_%d}
    policy: new_folder
    duration: null
    video:
      t265:
        codec: libx264
        encode_every: 1800
        encoder_kwargs:
          crf: '30'
          preset: ultrafast
    motion:
      odometry: null
      accel: null
      gyro: null
    show_video: true
    metadata: null

  calibrate:
    folder: ~/pupil_capture_settings
    world: world
    eye0: eye0
    eye1: eye1

  estimate_cam_params:
    folder: ~/pupil_capture_settings
    streams:
      t265:
        stereo: True

streams:
  video:
    t265:
      side: left
      resolution: (848, 800)
      fps: 30
      device_type: t265
      device_uid: null
      color_format: gray
  motion:
    odometry:
      device_type: t265
      device_uid: null
      motion_type: odometry
    accel:
      device_type: t265
      device_uid: null
      motion_type: accel
    gyro:
      device_type: t265
      device_uid: null
      motion_type: gyro
