version: 2.0.0

commands:
  override: false
  record:
    folder: ~/recordings/{today:%Y_%m_%d_%H_%M_%S}
    policy: here
    duration: null
    video:
      world:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      eye0:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      eye1:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      t265:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
    motion:
      odometry: null
      accel: null
      gyro: null
    show_video: false
    profile_selector: lighting
    metadata:
      # experimenter
      study_site: null
      experimenter_id: null
      # experiment
      experiment: null
      lighting: null
      scene: null
      instruction: null
      # subject
      subject_id: null
      age: null
      gender: null
      height: null
      ethnicity: null
      IPD: null
      tilt_angle: null
    intrinsics:
      - world
    extrinsics:
      - world
      - t265

  calibrate:
    folder: ~/pupil_capture_settings
    world: world
    eye0: eye0
    eye1: eye1

  validate:
    folder: ~/validations/{today:%Y_%m_%d_%H_%M_%S}
    policy: here
    world: world
    eye0: eye0
    eye1: eye1
    settings:
      circle_detector:
        scale: 0.5
        paused: true
        detection_method: vedb
        marker_size:
          - 5
          - 300
        threshold_window_size: 13
        min_area: 200
        max_area: 4000
        circularity: 0.8
        convexity: 0.7
        inertia: 0.4

  estimate_cam_params:
    folder: ~/pupil_capture_settings
    streams:
      t265:
        stereo: true
        scale: 0.75
      world:
        scale: 0.5

streams:
  override: false
  video:
    world:
      device_type: flir
      device_uid: null
      resolution: (2048, 1536)
      fps: 30
      color_format: bayer_rggb8
      settings:
        ExposureAuto: Continuous
        GainAuto: Continuous
    eye0:
      device_type: uvc
      device_uid: Pupil Cam2 ID0
      resolution: (400, 400)
      fps: 120
      color_format: gray
      exposure_mode: auto
      controls:
        Backlight Compensation: 1
        Brightness: 10
        Contrast: 65
        Gain: 0
        Hue: 0
        Saturation: 0
        Sharpness: 3
        Gamma: 120
        White Balance temperature: 4600
    eye1:
      device_type: uvc
      device_uid: Pupil Cam2 ID1
      resolution: (400, 400)
      fps: 120
      color_format: gray
      exposure_mode: auto
      controls:
        Backlight Compensation: 1
        Brightness: 10
        Contrast: 65
        Gain: 0
        Hue: 0
        Saturation: 0
        Sharpness: 3
        Gamma: 120
        White Balance temperature: 4600
    t265:
      device_type: t265
      device_uid: null
      resolution: (1696, 800)
      fps: 30
      color_format: gray
  motion:
    odometry:
      device_type: t265
      device_uid: null
      motion_type: odometry
    accel:
      device_type: t265
      device_uid: null
      motion_type: accel
    gyro:
      device_type: t265
      device_uid: null
      motion_type: gyro

profiles:
  indoor:
    video:
      eye0:
        controls:
          Backlight Compensation: 1
          Brightness: 10
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 120
          White Balance temperature: 4600
      eye1:
        controls:
          Backlight Compensation: 1
          Brightness: 10
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 120
          White Balance temperature: 4600
  outdoor:
    video:
      eye0:
        controls:
          Backlight Compensation: 1
          Brightness: 10
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 120
          White Balance temperature: 4600
      eye1:
        controls:
          Backlight Compensation: 1
          Brightness: 10
          Contrast: 65
          Gain: 0
          Hue: 0
          Saturation: 0
          Sharpness: 3
          Gamma: 120
          White Balance temperature: 4600
