version: 0.2.0

commands:
  record:
    folder: ~/recordings/{today:%Y_%m_%d}
    policy: new_folder
    duration: null
    video:
      world:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      eye0:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      eye1:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
      t265:
        codec: libx264
        encoder_kwargs:
          crf: '18'
          preset: ultrafast
    motion:
      odometry: null
      accel: null
      gyro: null
    show_video: true
    metadata:
      - location
      - experimenter
      - experiment
      - scene
      - task
      - subject_id
      - age
      - gender
      - ethnicity

  calibrate:
    folder: ~/pupil_capture_settings
    world: world
    eye0: eye0
    eye1: eye1

  estimate_cam_params:
    folder: ~/pupil_capture_settings
    streams:
      t265:
        stereo: True

streams:
  video:
    world:
      resolution: (2048, 1536)
      fps: 30
      device_type: flir
      device_uid: null
      color_format: bayer_rggb8
      settings:
        ExposureAuto: Continuous
        GainAuto: Continuous
    eye0:
      resolution: (192, 192)
      fps: 200
      device_type: uvc
      device_uid: Pupil Cam2 ID0
      color_format: gray
    eye1:
      resolution: (192, 192)
      fps: 200
      device_type: uvc
      device_uid: Pupil Cam2 ID1
      color_format: gray
    t265:
      resolution: (1696, 800)
      fps: 30
      device_type: t265
      device_uid: t265
      color_format: gray
  motion:
    odometry:
      device_type: t265
      device_uid: t265
      motion_type: odometry
    accel:
      device_type: t265
      device_uid: t265
      motion_type: accel
    gyro:
      device_type: t265
      device_uid: t265
      motion_type: gyro
