name: vedc
channels:
  - conda-forge
  - phausamann
dependencies:
  - python=3.6
  - pip
  # scientific stack
  - numpy
  - scipy
  - pandas
  - xarray
#  - netcdf4
  # video
  - phausamann::opencv=4.2.0
  - ffmpeg=3.4.2
  - x264=1!152.20180806
  # pupil
  - libusb=1.0.23
  - libuvc=0.0.7
  - libjpeg-turbo=2.0.3
  - pyuvc=0.13
  - msgpack-python=0.6.2
  - pupil-detectors=1.0.5
  # realsense
  - librealsense2=2.32.1
  # flir
  - spinnaker-sdk=1.27.0.48
  - pyspin=1.27.0.48
  # vedc
  - confuse=1.0.0
  - click=7.1.1
  # other
  - gitpython=3.1.0
  - tqdm
  # pip
  - pip:
    - blessed==1.17.4
    - multiprocessing-logging==0.3.1
    - pyrealsense2==2.32.1.1346
    - git+ssh://git@github.com/vedb/pupil_recording_interface@devel
    - git+ssh://git@github.com/vedb/ved-capture@devel
