name: vedc
channels:
  - conda-forge
  - eyeware
  - phausamann
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - librealsense2
  - ffmpeg=4.1.3
  - x264=1!152.20180806
  - opencv=4.1.0
  - netcdf4
  - msgpack-python=0.6.2
  - libuvc=0.0.7
  - libjpeg-turbo
  - tqdm
  - pip:
    - pyrealsense2
    - git+https://github.com/pupil-labs/pyuvc.git
