name: vedc
channels:
  - conda-forge
  - phausamann
dependencies:
  - python=3.7
  - pip
  # scientific stack
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  # video
  - ffmpeg=4.1.3
  - x264=1!152.20180806
  - opencv=4.1.0
  # pupil
  - libusb=1.0.23
  - libuvc=0.0.7
  - libjpeg-turbo=2.0.3
  - pyuvc=0.13
  - msgpack-python=0.6.2
  # realsense
  - librealsense2=2.32.1
  # flir
  - pyspin=1.27.0.48
  # vedc
  - confuse=1.0.0
  - click=7.1.1
  # other
  - gitpython=3.1.0
  - tqdm
  # pip
  - pip:
    - blessed==1.17.4
    - pyrealsense2==2.32.1.1346
    - git+ssh://git@github.com/vedb/pupil_recording_interface@v0.0.2-vedc
    - git+ssh://git@github.com/vedb/ved-capture
