name: build

on: push

jobs:

  test_app:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.VEDC_PRIVATE_KEY }}
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Create environment
        run: |
          conda install -y -c conda-forge mamba
          mamba env create
      - name: Run pytest
        run: |
          source activate vedc
          mamba install -c conda-forge pytest
          pytest

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: pip install black==19.10b0 flake8==3.7.9
      - name: Check black code style
        run: black --check .
      - name: Line with flake8
        run: flake8 ved-capture tests installer --ignore=E203,W503,W504
