name: build

on: push

jobs:

  test_installer:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.VEDC_PRIVATE_KEY }}
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Run installer
        run: python installer/install_ved_capture.py -y -v -b ${GITHUB_REF##*/} --no_ssh --no_version_check

  test_app:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.VEDC_PRIVATE_KEY }}
      - uses: s-weigand/setup-conda@v1
      - name: Check versions
        run: |
          conda --version
          which python
      - name: Create environment
        env:
          VEDC_DEV: true
          VEDC_PIN: ${GITHUB_REF##*/}
        run: |
          conda install -y -c conda-forge conda-devenv
          conda devenv
      - name: Copy paths.json
        run: |
          mkdir -p /home/runner/.config/vedc
          cp tests/test_data/config/paths.json /home/runner/.config/vedc
      - name: Run pytest
        run: |
          source activate vedc
          pytest
