name: test

on: push

jobs:

  test_installer:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.VEDC_PRIVATE_KEY }}
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Run installer
      run: python installer/install_ved_capture.py -y -v --no_ssh

  test_app:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.VEDC_PRIVATE_KEY }}
    - uses: s-weigand/setup-conda@v1
    - name: Check versions
      run: |
        conda --version
        which python
    - name: Install system dependencies
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/main/u/udev/libudev0_175-0ubuntu9_amd64.deb
        sudo dpkg -i libudev0_175-0ubuntu9_amd64.deb
    - name: Create environment
      run: conda env create
    - name: Install dev dependencies
      run: |
        source activate vedc
        conda install --file requirements_dev.txt
    - name: Run pytest
      run: |
        source activate vedc
        pytest tests
